site_name: Hacking Awesome CheatSheet
docs_dir: docs
nav: 
  - Home: index.md
  - Active Directory: 
      - Initial: active-directory/initial.md
      - AD Enumeration: active-directory/adenumeration.md
      - Credentials Haunting: active-directory/credentials.md
      - Living Off the Land: active-directory/lotl.md
      - ACL Abuse Primer: active-directory/acl.md
      - Common Vulnerabilities: active-directory/vulns.md
      - Attacking Domain Trust: active-directory/trust.md
      - LDAP: active-directory/ldap.md
      - Lateral Movement: active-directory/lateralmovement.md
      - Privilege Escalation: active-directory/privilege.md
  - Enumeration:
      - Nmap: enumeration/nmap.md
      - Enumeration: enumeration/enumeration.md
  - Footprinting: 
    - Domain info: footprinting/domain-info.md
    - FTP: footprinting/ftp.md
    - SSH: footprinting/ssh.md
    - SMTP: footprinting/smtp.md
    - DNS: footprinting/dns.md
    - IMAP/POP3: footprinting/imap-pop3.md
    - SNMP: footprinting/snmp.md
    - LDAP: footprinting/ldap.md
    - SMB: footprinting/smb.md
    - MSSQL: footprinting/mssql.md
    - MYSQL: footprinting/mysql.md
    - NFS: footprinting/nfs.md
    - RDP: footprinting/rdp.md
    - ORACLE TNS: footprinting/tns.md
    - IPMI: footprinting/ipmi.md
    - RSYNC: footprinting/rsync.md
    - RSERVICES: footprinting/rservices.md
    - WinRM: footprinting/winrm.md
    - MongoDB: footprinting/mongodb.md
  - Web Information Gathering: webinfogathering.md
  - Pivoting: pivoting.md
  - Walkthrough: 
    - HTB Academy: htb-academy/
    - HTB Labs: htb-labs/
  - Bash: bash/bash_scripts.md
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey 
    accent: green 
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  font:
    text: "Roboto"
    code: "Roboto Mono"
  custom_dir: docs/css

extra_css:
  - css/custom.css
