site_name: Hacking Awesome CheatSheet
nav: 
  - Home: index.md
  - Active Directory: 
      - Enumeration: active-directory/enumeration.md
      - Credentials Enumeration: active-directory/credentials.md
      - Lateral Movement: active-directory/lateralmovement.md
  - Footprinting: 
    - SMB: footprinting/smb.md
    - SNMP: footprinting/snmp.md
theme:
  name: material
  palette:
    scheme: slate
    primary: deep-orange 
    accent: orange 
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  font:
    text: "Roboto"
    code: "Roboto Mono"
